### ISSUE TITLE
description is inadequate

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [StefanosChaliasos/pandac#1]
The project description "crazy maths and more" doesn't say much.  Is it possible to expand on this a bit?

**Comment by jeffreybreen** [comment]
Yeah -- the whole purpose of this repo appears to install a keylogger. 

I think github needs a "flag this repo" feature : (

**Comment by Phillip-M-Feldman** [comment]
Good catch!

**Comment by StefanosChaliasos** [comment]
Hello, indeed it's a keylogger. We use it for teaching purposes.

**Comment by Phillip-M-Feldman** [comment]
Please add a note to this effect in the description.
